### ISSUE TITLE
Readme example of dyalog JSON server is outdated.

### ISSUE THREAD

**Issue by 0xACE** [dzaima/APL#3]
```
)LOAD path/to/JSONServer/Distribution/JSONServer.dws
S←⊃JSONServer.Run ⍬
eval←{⎕←'  ',⍵ ⋄ 0::{⎕←↑⎕DM⋄⎕DM}⍬ ⋄ ,↓⎕←⍕⍎⍵}       ⍝ This function is no longer valid in JSONServer
```

```
$ curl -vv http://127.0.0.1:8080/eval -d '"2+2"'
...
HTTP/1.1 400 Bad Request - "eval" is not a monadic result-returning function
```

This was caused by https://github.com/Dyalog/JSONServer/commit/3755b7d5803dd9279d4e7e2dfb15c621af0865ff

the error is generated by https://github.com/Dyalog/JSONServer/blob/4e18cac2d2f3571fda98c4126bb39e5f47578ab7/Source/JSONServer.dyalog#L246

**Comment by dzaima** [comment]
readme has been updated.
