### ISSUE TITLE
Is there a way to use the virtual keyboard on a computer? 

### ISSUE THREAD

**Issue by madushan1000** [dzaima/APL#7]
The android app has a nice virtual keyboard to input symbols, I generated the app for linux using processing and I can't see the keyboard. Is there a way to enable in on a computer too?

**Comment by madushan1000** [comment]
nevermind, I got it enabled after fiddling with the source code a little bit. Keyboard size is set to 0 for computers here (https://github.com/dzaima/BQN/blob/master/app/app.pde#L58).

**Comment by dzaima** [comment]
yeah, all configuration has to be done through the source code for now. at Some Point In The Future I'll hopefully make a more proper & customizable app that covers both APL and BQN (among potentially whatever other langs may want a place), but there are way too many other things for me to do right now.
